### ISSUE TITLE
Afegir el servei de consulta de estar al corrent d’obligacions tributàries per sol·licitud de subvencions i ajudes amb indicació de incompliments 

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1362]
Codi ECOT103 (no confondre amb ECOT103I)

**Comment by acuevas-dgtic** [comment]
La consulta està donant error:

S'han produit errors en la consulta PINBAL: [peticionSincrona] es.caib.ripea.core.api.exception.PinbalException: [0401] La petició rebuda no es correspon amb l'estructura definida en l'XSD del servei. Revisi que no faltin camps per emplenar, i que esl camps emplenats siguin correctes i tinguin el format correcte. En cas contrari contacti amb el centre de suport.Error retornat: : Value 'CIF' is not facet-valid with respect to enumeration '[NIF, NIE]'. It must be a value from the enumeration. cvc-type.3.1.3: The value 'CIF' of element 'TipoD....|||El servidor ha devuelto un mensaje SOAP Fault. La estructura del fichero recibido no corresponde con el esquema. cvc-enumeration-valid: Value 'CIF' is not facet-valid with respect to enumeration '[NIF, NIE]'. It must be a value from 
the enumeration. cvc-type.3.1.3: The value 'CIF' of element 'TipoD... 



```
javax.ejb.EJBException: es.caib.ripea.core.api.exception.PinbalException: 
[0401] La petició rebuda no es correspon amb l'estructura definida en l'XSD 
del servei. Revisi que no faltin camps per emplenar, i que esl camps 
emplenats siguin correctes i tinguin el format correcte. En cas contrari 
contacti amb el centre de suport.Error retornat: : Value 'CIF' is not 
facet-valid with respect to enumeration '[NIF, NIE]'. It must be a value from 
the enumeration. cvc-type.3.1.3: The value 'CIF' of element 'TipoD....|||El 
servidor ha devuelto un mensaje SOAP Fault. La estructura del fichero recibido 
no corresponde con el esquema. cvc-enumeration-valid: Value 'CIF' is not 
facet-valid with respect to enumeration '[NIF, NIE]'. It must be a value from 
the enumeration. cvc-type.3.1.3: The value 'CIF' of element 'TipoD... at 
org.jboss.ejb3.tx.Ejb3TxPolicy.handleExceptionInOurTx(Ejb3TxPolicy.java:77) at 
org.jboss.aspects.tx.TxPolicy.invokeInOurTx(TxPolicy.java:83) at 
org.jboss.aspects.tx.TxInterceptor$Required.invoke(TxInterceptor.java:190) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.aspects.tx.TxPropagationInterceptor.invoke(TxPropagationInterceptor.ja
va:76) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.security.RunAsSecurityInterceptorv2.invoke(RunAsSecurityIntercept
orv2.java:105) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.security.RoleBasedAuthorizationInterceptorv2.invoke(RoleBasedAuth
orizationInterceptorv2.java:201) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.security.Ejb3AuthenticationInterceptorv2.invoke(Ejb3Authenticatio
nInterceptorv2.java:182) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.ENCPropagationInterceptor.invoke(ENCPropagationInterceptor.java:4
1) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.BlockContainerShutdownInterceptor.invoke(BlockContainerShutdownIn
terceptor.java:67) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.core.context.CurrentInvocationContextInterceptor.invoke(CurrentIn
vocationContextInterceptor.java:47) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.aspects.currentinvocation.CurrentInvocationInterceptor.invoke(CurrentI
nvocationInterceptor.java:67) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.interceptor.EJB3TCCLInterceptor.invoke(EJB3TCCLInterceptor.java:8
6) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.session.SessionSpecContainer.invoke(SessionSpecContainer.java:193
) at 
org.jboss.ejb3.session.SessionSpecContainer.invoke(SessionSpecContainer.java:250
) at 
org.jboss.ejb3.proxy.impl.handler.session.SessionProxyInvocationHandlerBase.invo
ke(SessionProxyInvocationHandlerBase.java:188) at 
com.sun.proxy.$Proxy403.pinbalNovaConsulta(Unknown Source) at 
sun.reflect.GeneratedMethodAccessor7285.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.springframework.ejb.access.LocalSlsbInvokerInterceptor.invokeInContext(Local
SlsbInvokerInterceptor.java:71) at 
org.springframework.ejb.access.AbstractSlsbInvokerInterceptor.invoke(AbstractSls
bInvokerInterceptor.java:189) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.j
ava:204) at com.sun.proxy.$Proxy404.pinbalNovaConsulta(Unknown Source) at 
es.caib.ripea.war.controller.ContingutPinbalController.postNew(ContingutPinbalCo
ntroller.java:128) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native 
Method) at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(Invocable
HandlerMethod.java:221) at 
org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(I
nvocableHandlerMethod.java:136) at 
org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMet
hod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) at 
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapt
er.invokeHandleMethod(RequestMappingHandlerAdapter.java:743) at 
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapt
er.handleInternal(RequestMappingHandlerAdapter.java:672) at 
org.springframework.web.servle.mvc.method.AbstractHandlerMethodAdapter.handle(Ab
stractHandlerMethodAdapter.java:82) at 
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.j
ava:933) at 
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.ja
va:867) at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:951) at 
org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:85
3) at javax.servlet.http.HttpServlet.service(HttpServlet.java:637) at 
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:8
27) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59)
 at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java
:638) at 
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatc
her.java:444) at 
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.j
ava:382) at 
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.jav
a:310) at 
es.caib.ripea.war.helper.ModalHelper.comprovarModalInterceptor(ModalHelper.java:
41) at 
es.caib.ripea.war.interceptor.ModalInterceptor.preHandle(ModalInterceptor.java:2
5) at 
org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExec
utionChain.java:134) at 
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.j
ava:928) at 
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.ja
va:867) at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:951) at 
org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:85
3) at javax.servlet.http.HttpServlet.service(HttpServlet.java:637) at 
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:8
27) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.jav
a:129) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
 at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(Characte
rEncodingFilter.java:88) at 
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilte
r.java:106) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:330) at 
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invo
ke(FilterSecurityInterceptor.java:118) at 
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFi
lter(FilterSecurityInterceptor.java:84) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(Exce
ptionTranslationFilter.java:113) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.AnonymousAuthenticationFilter.do
Filter(AnonymousAuthenticationFilter.java:113) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFil
ter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(R
equestCacheAwareFilter.java:45) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.www.BasicAuthenticationFilter.do
Filter(BasicAuthenticationFilter.java:150) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFil
ter.doFilter(DefaultLoginPageGeneratingFilter.java:155) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.AbstractAuthenticationProcessing
Filter.doFilter(AbstractAuthenticationProcessingFilter.java:199) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.preauth.AbstractPreAuthenticated
ProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:107) 
at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(Log
outFilter.java:110) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(Head
erWriterFilter.java:57) at 
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilte
r.java:106) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilt
er(SecurityContextPersistenceFilter.java:87) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainPr
oxy.java:192) at 
org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java
:160) at 
org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFi
lterProxy.java:343) at 
org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterPr
oxy.java:260) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:9
6) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
35) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91) at 
org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociatio
nValve.java:183) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.jav
a:534) at 
org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95) 
at 
org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(Security
ContextEstablishmentValve.java:126) at 
org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityC
ontextEstablishmentValve.java:70) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) 
at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) 
at 
org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionVa
lve.java:158) at 
es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31) 
at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:60) at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
) at 
org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalPro
cess(ActiveRequestResponseCacheValve.java:74) at 
org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(Acti
veRequestResponseCacheValve.java:47) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330) at 
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829) at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Pr
otocol.java:599) at 
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451) at 
java.lang.Thread.run(Thread.java:745) Caused by: 
es.caib.ripea.core.api.exception.PinbalException: [0401] La petició rebuda no 
es correspon amb l'estructura definida en l'XSD del servei. Revisi que no 
faltin camps per emplenar, i que esl camps emplenats siguin correctes i 
tinguin el format correcte. En cas contrari contacti amb el centre de 
suport.Error retornat: : Value 'CIF' is not facet-valid with respect to 
enumeration '[NIF, NIE]'. It must be a value from the enumeration. 
cvc-type.3.1.3: The value 'CIF' of element 'TipoD....|||El servidor ha 
devuelto un mensaje SOAP Fault. La estructura del fichero recibido no 
corresponde con el esquem. cvc-enumeration-valid: Value 'CIF' is not 
facet-valid with respect to enumeration '[NIF, NIE]'. It must be a value from 
the enumeration. cvc-type.3.1.3: The value 'CIF' of element 'TipoD... at 
es.caib.ripea.core.helper.PinbalHelper.processarException(PinbalHelper.java:644)
 at 
es.caib.ripea.core.helper.PinbalHelper.novaPeticioEcot103(PinbalHelper.java:426)
 at 
es.caib.ripea.core.service.DocumentServiceImpl.pinbalNovaConsulta(DocumentServic
eImpl.java:809) at sun.reflect.GeneratedMethodAccessor7285.invoke(Unknown 
Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils
.java:317) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(Ref
lectiveMethodInvocation.java:183) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:150) at 
org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterTh
rowingAdvice.java:55) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWith
Invocation(TransactionInterceptor.java:96) at 
org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithi
nTransaction(TransactionAspectSupport.java:260) at 
org.springframework.transaction.interceptor.TransactionInterceptor.invoke(Transa
ctionInterceptor.java:94) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInv
ocationInterceptor.java:91) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.j
ava:204) at com.sun.proxy.$Proxy575.pinbalNovaConsulta(Unknown Source) at 
es.caib.ripea.core.ejb.DocumentServiceBean.pinbalNovaConsulta(DocumentServiceBea
n.java:158) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeTarget(MethodInvocation.java:122)
 at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:111) 
at 
org.jboss.ejb3.interceptors.container.ContainerMethodInvocationWrapper.invokeNex
t(ContainerMethodInvocationWrapper.java:72) at 
org.jboss.ejb3.interceptors.aop.InterceptorSequencer.invoke(InterceptorSequencer
.java:76) at 
org.jboss.ejb3.interceptors.aop.InterceptorSequencer.aroundInvoke(InterceptorSeq
uencer.java:62) at sun.reflect.GeneratedMethodAccessor6735.invoke(Unknown 
Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.jboss.aop.advice.PerJoinpointAdvice.invoke(PerJoinpointAdvice.java:174) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor.fillMethod(Invocati
onContextInterceptor.java:72) at 
org.jboss.aop.advice.org.jboss.ejb3.interceptors.aop.InvocationContextIntercepto
r_z_fillMethod_29000668.invoke(InvocationContextInterceptor_z_fillMethod_2900066
8.java) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor.setup(InvocationCon
textInterceptor.java:88) at 
org.jboss.aop.advice.org.jboss.ejb3.interceptors.aop.InvocationContextIntercepto
r_z_setup_29000668.invoke(InvocationContextInterceptor_z_setup_29000668.java) 
at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.connectionmanager.CachedConnectionInterceptor.invoke(CachedConnec
tionInterceptor.java:62) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
es.caib.sw.metrics.interceptor.MetricsServerInterceptor.invoke(MetricsServerInte
rceptor.java:23) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.entity.TransactionScopedEntityManagerInterceptor.invoke(Transacti
onScopedEntityManagerInterceptor.java:56) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.AllowedOperationsInterceptor.invoke(AllowedOperationsInterceptor.
java:47) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
aorg.jboss.ejb3.stateless.StatelessInstanceInterceptor.invoke(StatelessInstanceI
nterceptor.java:68) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at org.jboss.aspects.tx.TxPolicy.invokeInOurTx(TxPolicy.java:79) ... 135 more 
Caused by: es.caib.pinbal.client.recobriment.RecobrimentException: [0401] La 
petició rebuda no es correspon amb l'estructura definida en l'XSD del servei. 
Revisi que no faltin camps per emplenar, i que esl camps emplenats siguin 
correctes i tinguin el format correcte. En cas contrari contacti amb el centre 
de suport.Error retornat: : Value 'CIF' is not facet-valid with respect to 
enumeration '[NIF, NIE]'. It must be a value from the enumeration. 
cvc-type.3.1.3: The value 'CIF' of element 'TipoD....|||El servidor ha 
devuelto un mensaje SOAP Fault. La estructura del fichero recibido no 
corresponde con el esquema. cvc-enumeration-valid: Value 'CIF' is not 
facet-valid with respect to enumeration '[NIF, NIE]'. It must be a value from 
the enumeration. cvc-type.3.1.3: The value 'CIF' of element 'TipoD... at 
es.caib.pinbal.client.recobriment.ClientBase.basePeticionSincrona(ClientBase.jav
a:82) at 
es.caib.pinbal.client.recobriment.ecot103.ClientEcot103.peticionSincrona(ClientE
cot103.java:45) at 
es.caib.ripea.core.helper.PinbalHelper.novaPeticioEcot103(PinbalHelper.java:423)
 ... 186 more 
```

**Comment by josepg-limit** [comment]
Este mensaje quiere decire que el servicio solo permite los tipos de documentos NIF y NIE así que es necesario restingirlos en la configuración del tipo de documento.
![tipo documento](https://github.com/GovernIB/ripea/assets/17267008/59f19a08-7341-4aed-be4e-831fcfe274fd)

**Comment by acuevas-dgtic** [comment]
Ok, hemos informado al usuario
