### ISSUE TITLE
Error al accedir a l'enllaç d'una tasca enviada per correu

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/ripea#1440]
Un usuari ens informa que ha rebut un correu de canvi d'estat de tasques, però si li dona a l'enllaç surt el següent error:

![~9403321](https://github.com/GovernIB/ripea/assets/58417501/05fc46bb-49a7-4f55-a8b5-a8d823ce7a72)

```
javax.ejb.EJBException: java.lang.SecurityException: Sense permisos per accedir 
la tasca (tascaId=10811293, usuari=XXX) at 
org.jboss.ejb3.tx.Ejb3TxPolicy.handleExceptionInOurTx(Ejb3TxPolicy.java:77) at 
org.jboss.aspects.tx.TxPolicy.invokeInOurTx(TxPolicy.java:83) at 
org.jboss.aspects.tx.TxInterceptor$Required.invoke(TxInterceptor.java:190) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.aspects.tx.TxPropagationInterceptor.invoke(TxPropagationInterceptor.ja
va:76) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.security.RunAsSecurityInterceptorv2.invoke(RunAsSecurityIntercept
orv2.java:105) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.security.RoleBasedAuthorizationInterceptorv2.invoke(RoleBasedAuth
orizationInterceptorv2.java:201) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.security.Ejb3AuthenticationInterceptorv2.invoke(Ejb3Authenticatio
nInterceptorv2.java:182) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.ENCPropagationInterceptor.invoke(ENCPropagationInterceptor.java:4
1) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.BlockContainerShutdownInterceptor.invoke(BlockContainerShutdownIn
terceptor.java:67) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.core.context.CurrentInvocationContextInterceptor.invoke(CurrentIn
vocationContextInterceptor.java:47) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.aspects.currentinvocation.CurrentInvocationInterceptor.invoke(CurrentI
nvocationInterceptor.java:67) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.interceptor.EJB3TCCLInterceptor.invoke(EJB3TCCLInterceptor.java:8
6) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.session.SessionSpecContainer.invoke(SessionSpecContainer.java:193
) at 
org.jboss.ejb3.session.SessionSpecContainer.invoke(SessionSpecContainer.java:250
) at 
org.jboss.ejb3.proxy.impl.handler.session.SessionProxyInvocationHandlerBase.invo
ke(SessionProxyInvocationHandlerBase.java:188) at 
com.sun.proxy.$Proxy443.findTascaExpedient(Unknown Source) at 
sun.reflect.GeneratedMethodAccessor1963.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.springframework.ejb.access.LocalSlsbInvokerInterceptor.invokeInContext(Local
SlsbInvokerInterceptor.java:71) at 
org.springframework.ejb.access.AbstractSlsbInvokerInterceptor.invoke(AbstractSls
bInvokerInterceptor.java:189) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.j
ava:204) at com.sun.proxy.$Proxy444.findTascaExpedient(Unknown Source) at 
es.caib.ripea.war.controller.ContingutController.contingutGet(ContingutControlle
r.java:163) at sun.reflect.GeneratedMethodAccessor1026.invoke(Unknown Source) 
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(Invocable
HandlerMethod.java:221) at 
org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(I
nvocableHandlerMethod.java:136) at 
org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMet
hod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) at 
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapt
er.invokeHandleMethod(RequestMappingHandlerAdapter.java:743) at 
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapt
er.handleInternal(RequestMappingHandlerAdapter.java:672) at 
org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(A
bstractHandlerMethodAdapter.java:82) at 
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.j
ava:933) at 
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.ja
va:867) at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:951) at 
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842
) at javax.servlet.http.HttpServlt.service(HttpServlet.java:617) at 
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:8
27) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.jav
a:129) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
 at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(Characte
rEncodingFilter.java:88) at 
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilte
r.java:106) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:330) at 
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invo
ke(FilterSecurityInterceptor.java:118) at 
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFi
lter(FilterSecurityInterceptor.java:84) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(Exce
ptionTranslationFilter.java:113) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.AnonymousAuthenticationFilter.do
Filter(AnonymousAuthenticationFilter.java:113) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFil
ter.doFilter(SecurityContextHolderAwareRequestFilter.java:154) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(R
equestCacheAwareFilter.java:45) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.www.BasicAuthenticationFilter.do
Filter(BasicAuthenticationFilter.java:150) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFil
ter.doFilter(DefaultLoginPageGeneratingFilter.java:155) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.AbstractAuthenticationProcessing
Filter.doFilter(AbstractAuthenticationProcessingFilter.java:199) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.preauth.AbstractPreAuthenticated
ProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:107) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(Log
outFilter.java:110) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(Head
erWriterFilter.java:57) at 
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilte
r.java:106) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilt
er(SecurityContextPersistenceFilter.java:87) at 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(Fi
lterChainProxy.java:342) at 
org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainPr
oxy.java:192) at 
org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java
:160) at 
org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFi
lterProxy.java:343) at 
org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterPr
oxy.java:260) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:9
6) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
35) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91) at 
org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociatio
nValve.java:183) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.jav
a:534) at 
org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95) 
at 
org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(Security
ContextEstablishmentValve.java:126) at 
org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityC
ontextEstablishmentValve.java:70) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) 
at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) 
at 
org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionVa
lve.java:158) at 
es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31) 
at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:60) at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
) at 
org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalPro
cess(ActiveRequestResponseCacheValve.java:74) at 
org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(Acti
veRequestResponseCacheValve.java:47) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330) at 
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829) at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Pr
otocol.java:599) at 
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451) at 
java.lang.Thread.run(Thread.java:745) Caused by: java.lang.SecurityException: 
Sense permisos per accedir la tasca (tascaId=10811293, usuari=u107002) at 
es.caib.ripea.core.helper.ContingutHelper.comprovarContingutPertanyTascaAccesibl
e(ContingutHelper.java:1306) at 
es.caib.ripea.core.helper.ContingutHelper$$FastClassBySpringCGLIB$$1046a37c.invo
ke() at org.springframework.cglib.poxy.MethodProxy.invoke(MethodProxy.java:204) 
at 
org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.interc
ept(CglibAopProxy.java:629) at 
es.caib.ripea.core.helper.ContingutHelper$$EnhancerBySpringCGLIB$$a6a5ed56.compr
ovarContingutPertanyTascaAccesible() at 
es.caib.ripea.core.service.ExpedientTascaServiceImpl.findTascaExpedient(Expedien
tTascaServiceImpl.java:188) at 
sun.reflect.GeneratedMethodAccessor1963.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils
.java:317) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(Ref
lectiveMethodInvocation.java:183) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:150) at 
org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterTh
rowingAdvice.java:55) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWith
Invocation(TransactionInterceptor.java:96) at 
org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithi
nTransaction(TransactionAspectSupport.java:260) at 
org.springframework.transaction.interceptor.TransactionInterceptor.invoke(Transa
ctionInterceptor.java:94) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInv
ocationInterceptor.java:91) at 
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveM
ethodInvocation.java:172) at 
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.j
ava:204) at com.sun.proxy.$Proxy617.findTascaExpedient(Unknown Source) at 
es.caib.ripea.core.ejb.ExpedientTascaServiceBean.findTascaExpedient(ExpedientTas
caServiceBean.java:105) at 
sun.reflect.GeneratedMethodAccessor2908.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeTarget(MethodInvocation.java:122)
 at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:111) 
at 
org.jboss.ejb3.interceptors.container.ContainerMethodInvocationWrapper.invokeNex
t(ContainerMethodInvocationWrapper.java:72) at 
org.jboss.ejb3.interceptors.aop.InterceptorSequencer.invoke(InterceptorSequencer
.java:76) at 
org.jboss.ejb3.interceptors.aop.InterceptorSequencer.aroundInvoke(InterceptorSeq
uencer.java:62) at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown 
Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.jboss.aop.advice.PerJoinpointAdvice.invoke(PerJoinpointAdvice.java:174) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor.fillMethod(Invocati
onContextInterceptor.java:72) at 
org.jboss.aop.advice.org.jboss.ejb3.interceptors.aop.InvocationContextIntercepto
r_z_fillMethod_1540562821.invoke(InvocationContextInterceptor_z_fillMethod_15405
62821.java) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor.setup(InvocationCon
textInterceptor.java:88) at 
org.jboss.aop.advice.org.jboss.ejb3.interceptors.aop.InvocationContextIntercepto
r_z_setup_1540562821.invoke(InvocationContextInterceptor_z_setup_1540562821.java
) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.connectionmanager.CachedConnectionInterceptor.invoke(CachedConnec
tionInterceptor.java:62) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
es.caib.sw.metrics.interceptor.MetricsServerInterceptor.invoke(MetricsServerInte
rceptor.java:23) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.entity.TransactionScopedEntityManagerInterceptor.invoke(Transacti
onScopedEntityManagerInterceptor.java:56) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.AllowedOperationsInterceptor.invoke(AllowedOperationsInterceptor.
java:47) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at 
org.jboss.ejb3.stateless.StatelessInstanceInterceptor.invoke(StatelessInstanceIn
terceptor.java:68) at 
org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) 
at org.jboss.aspects.tx.TxPolicy.invokeInOurTx(TxPolicy.java:79) ... 115 more
```

**Comment by josepg-limit** [comment]
La causa de l'error és que la tasca ja no pertany a l'usuari. Segurament perquè ha estat reassignada. S'ha millorat el missatge d'error que es mostra per a que l'usuari sigui conscient del que ha passat.
