### ISSUE TITLE
Error amb el callback de PortaFIB

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#24]
Fent les proves d'integració RIPEA - PortaFIB, s'ha detectat un problema cridant el nou callback de portafirmes. L'error que dona a PortaFIB és el següent:

javax.xml.ws.WebServiceException: Port {http://v1.server.callback.ws.portafib.caib.es/}PortaFIBCallBackWs not found.
        at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:332)
        at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:323)
        at javax.xml.ws.Service.getPort(Service.java:92)
        at es.caib.portafib.ws.callback.api.v1.PortaFIBCallBackWsService.getPortaFIBCallBackWs(PortaFIBCallBackWsService.java:58)
        at es.caib.portafib.logic.utils.NotificacionsQueue.enviarNotificacioApiPortaFIBv1(NotificacionsQueue.java:475)
[...]

Pareix com si PortaFIB no es trobàs el servei web correcte.

**Comment by josepg-limit** [comment]
RIPEA dona un error que no pot crear el ws, quan accedeixes a https://proves.caib.es/ripea/ws/portafibCallback?wsdl apareix el següent error. Al portafib apareix un error que diu org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.

**Comment by josepg-limit** [comment]
Segueix donant error d'accés des de PortaFIB:

portafib dona un error al intentar notificar. Als logs de RIPEA no veig res.


Port {http://v1.server.callback.ws.portafib.caib.es/}PortaFIBCallBackWs not found.
--------------------------------------------
javax.xml.ws.WebServiceException: Port {http://v1.server.callback.ws.portafib.caib.es/}PortaFIBCallBackWs not found.
        at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:332)
        at org.apache.cxf.jaxws.ServiceImpl.getPort(ServiceImpl.java:323)
[...]
