### ISSUE TITLE
Error en custodiar document

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#761]
Després d'enviar a firmar un document a portafib, es firmat correctament, però quan s'intenta arxivar dona un error al plugin d'arxiu. La qüestió és que el document existeix a dins l'arxiu i se pot descarregar normalment, és TF06 , pero a ripea s'ha quedat pendent d'arxiu.  Si vas a Seguiment portafirmes: S'han produit errors processant la firma del document, on se veu el trace:

es.caib.plugins.arxiu.api.ArxiuValidacioException: Error de validació: El document de l'arxiu ja està firmat i el tipus de firma especificat (TF06) no coicideix amb l'existent a l'arxiu (TF01)
	at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.comprovarFirma(ArxiuPluginCaib.java:1577)
	at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.documentModificar(ArxiuPluginCaib.java:661)
	at es.caib.ripea.core.helper.PluginHelper.arxiuDocumentGuardarFirmaPades(PluginHelper.java:1388)
	at es.caib.ripea.core.firma.DocumentFirmaPortafirmesHelper.portafirmesProcessar(DocumentFirmaPortafirmesHelper.java:402)
	at es.caib.ripea.core.firma.DocumentFirmaPortafirmesHelper.portafirmesReintentar(DocumentFirmaPortafirmesHelper.java:260)
	at es.caib.ripea.core.service.DocumentServiceImpl.portafirmesReintentar(DocumentServiceImpl.java:678)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionIn...

**Comment by santich-dgtic** [comment]
Si ho voleu mirar, diria que aquest error es dona perquè s'omplen els camps del plugin d'arxiu erròniament, ja que s'ha d'omplir un o altre segons si el tipus de firma es attached o dettached. Es a dir, si és un document signat (PADES) a l'arxiu, el document signat s'ha d'instertar dins l'apartat "firmes" del Document, mentre que DocumentContingut s'ha de deixar a null. Si és una firma "detached" (CADES o XADES), dins DocumentContingut es posa l'array de bytes del document original i dins les firmes del Document es posen els arrays de bytes que corresponen a les firmes. A RIPEA tenim el mateix problema (issue #1427 de HELIUM)...
