### ISSUE TITLE
Error quan s'accepta o rebutja anotacions pendents

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/ripea#775]
Quan acceptam una anotació pendent, dona error d'ajax, si cream un expedient
![anotacio](https://user-images.githubusercontent.com/65942619/118108899-d5720e00-b3e0-11eb-8595-fd197c820e75.png)

i si la rebutjam null pointer
2021-05-13 11:41:55,225 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/ripea].[ripea]] (http-10.215.29.9-18080-12) El Servlet.service() para servlet ripea lanzó una excepción
java.lang.NullPointerException
        at org.jboss.web.tomcat.security.JBossWebRealm.hasRole(JBossWebRealm.java:559)
        at org.apache.catalina.connector.Request.isUserInRole(Request.java:2204)
        at org.apache.catalina.connector.RequestFacade.isUserInRole(RequestFacade.java:763)
        at javax.servlet.http.HttpServletRequestWrapper.isUserInRole(HttpServletRequestWrapper.java:164)
        at es.caib.ripea.war.helper.RolHelper.getRolsUsuariActual(RolHelper.java:90)
        at es.caib.ripea.war.helper.RolHelper.getRolActual(RolHelper.java:47)
        at es.caib.ripea.war.helper.RolHelper.isRolActualUsuari(RolHelper.java:84)
        at es.caib.ripea.war.helper.ExpedientHelper.teAccesExpedients(ExpedientHelper.java:43)
        at es.caib.ripea.war.helper.ExpedientHelper.accesUsuariExpedients(ExpedientHelper.java:29)
        at es.caib.ripea.war.interceptor.ExpedientsInterceptor.preHandle(ExpedientsInterceptor.java:30)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:134)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:928)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:638)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:446)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:382)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:310)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:416)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:270)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
        at es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31)
        at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:62)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalProcess(ActiveRequestResponseCacheValve.java:74)
        at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:47)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:599)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451)
        at java.lang.Thread.run(Thread.java:745)
2021-05-13 11:41:55,225 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost]] (http-10.215.29.9-18080-12) Exception Processing ErrorPage[exceptionType=java.lang.Throwable, location=/error]
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:638)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:446)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:382)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:310)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:416)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:270)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
        at es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31)
        at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:62)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalProcess(ActiveRequestResponseCacheValve.java:74)
        at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:47)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:599)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.jboss.web.tomcat.security.JBossWebRealm.hasRole(JBossWebRealm.java:559)
        at org.apache.catalina.connector.Request.isUserInRole(Request.java:2204)
        at org.apache.catalina.connector.RequestFacade.isUserInRole(RequestFacade.java:763)
        at javax.servlet.http.HttpServletRequestWrapper.isUserInRole(HttpServletRequestWrapper.java:164)
        at es.caib.ripea.war.helper.RolHelper.getRolsUsuariActual(RolHelper.java:90)
        at es.caib.ripea.war.helper.RolHelper.getRolActual(RolHelper.java:47)
        at es.caib.ripea.war.helper.RolHelper.isRolActualUsuari(RolHelper.java:84)
        at es.caib.ripea.war.helper.ExpedientHelper.teAccesExpedients(ExpedientHelper.java:43)
        at es.caib.ripea.war.helper.ExpedientHelper.accesUsuariExpedients(ExpedientHelper.java:29)
        at es.caib.ripea.war.interceptor.ExpedientsInterceptor.preHandle(ExpedientsInterceptor.java:30)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:134)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:928)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
        ... 29 more

**Comment by santich-dgtic** [comment]
Si ho volem incorporar a un expedient ja existent una vegada triam el tipus se queda donant voltes intentant recuperar els expedients d'aquell tipus.

**Comment by acuevas-dgtic** [comment]
Viene de la #764
