### ISSUE TITLE
Error desplegament a proves amb EhCache

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#850]
L'error que dona al desplegar l'aplicació és el següent:

Cannot resolve reference to bean 'aclCache' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aclCache' defined in class path resource [es/caib/ripea/core/context/application-context-model-acl.xml]: Cannot create inner bean 'org.springframework.cache.ehcache.EhCacheFactoryBean#7e70ba6d' of type [org.springframework.cache.ehcache.EhCacheFactoryBean] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.ehcache.EhCacheFactoryBean#7e70ba6d' defined in class path resource [es/caib/ripea/core/context/application-context-model-acl.xml]: Cannot resolve reference to bean 'ehcache' while setting bean property 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ehcache' defined in class path resource [es/caib/ripea/core/context/application-context-model.xml]: Invocation of init method failed; nested exception is net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=org.jboss.virtual.plugins.context.zip.CertificateReaderInputStream@2da07b38]
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:386)
	at org.springframework.ejb.interceptor.SpringBeanAutowiringInterceptor.getBeanFactoryReference(SpringBeanAutowiringInterceptor.java:160)
	at org.springframework.ejb.interceptor.SpringBeanAutowiringInterceptor.getBeanFactory(SpringBeanAutowiringInterceptor.java:141)
	at org.springframework.ejb.interceptor.SpringBeanAutowiringInterceptor.doAutowireBean(SpringBeanAutowiringInterceptor.java:121)
	at org.springframework.ejb.interceptor.SpringBeanAutowiringInterceptor.autowireBean(SpringBeanAutowiringInterceptor.java:95)
	... 102 more

**Comment by acuevas-dgtic** [comment]
Solucionado
