### ISSUE TITLE
Error afegint més d'un interessat quan s'envia al registre

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/ripea#86]
Es detecta un error enviant al registre amb més d'un interessat amb representant. La traça de l'error és la següent:

`2017-07-18 11:14:50,235 WARN  [org.hibernate.util.JDBCExceptionReporter] (http-10.215.9.173-18080-4) SQL Error: 1, SQLState: 23000
2017-07-18 11:14:50,235 ERROR [org.hibernate.util.JDBCExceptionReporter] (http-10.215.9.173-18080-4) ORA-00001: restricciÃ³n Ãºnica (RIPEA.IPA_REGINT_MULT_UK) violada

2017-07-18 11:14:50,320 DEBUG [es.caib.ripea.core.service.AplicacioServiceImpl] (http-10.215.9.173-18080-4) Emmagatzemant excepciÃ³ (exception=org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into ipa_registre_inter (createdBy_codi, createdDate, lastModifiedBy_codi, lastModifiedDate, adresa, canal_pref, codi_postal, doc_num, doc_tipus, email, email_hab, llinatge1, llinatge2, municipi, nom, observacions, pais, provincia, rao_social, registre_id, representant_id, representat_id, telefon, tipus, version, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update)
2017-07-18 11:14:50,437 WARNING [org.apache.cxf.phase.PhaseInterceptorChain] (http-10.215.9.173-18080-4) Application {http://www.caib.es/ripea/ws/v1/bustia}BustiaV1Service#{http://www.caib.es/ripea/ws/v1/bustia}enviarAnotacioRegistreEntrada has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into ipa_registre_inter (createdBy_codi, createdDate, lastModifiedBy_codi, lastModifiedDate, adresa, canal_pref, codi_postal, doc_num, doc_tipus, email, email_hab, llinatge1, llinatge2, municipi, nom, observacions, pais, provincia, rao_social, registre_id, representant_id, representat_id, telefon, tipus, version, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
        at org.jboss.wsf.stack.cxf.AbstractInvoker.createFault(AbstractInvoker.java:220)
        at org.jboss.wsf.stack.cxf.AbstractInvoker._invokeInternal(AbstractInvoker.java:191)
   `

La solució és esborrar la restricció IPA_REGINT_MULT_UK de la taula IPA_REGISTRE_INTER amb la següent comanda SQL:
`ALTER TABLE IPA_REGISTRE_INTER DROP CONSTRAINT IPA_REGINT_MULT_UK;`

**Comment by josepg-limit** [comment]
Es modifica l'script de creació  ripea_02_constraint.sql per a que aquesta restricció no es crei.

**Comment by josepg-limit** [comment]
[commit](https://github.com/GovernIB/ripea/commit/943471b55ea544cbb750d525283b04f1477f60f7)
